add the ability to use fzf on unknown points.

diff --git a/sd b/sd
--- a/sd
+++ b/sd
@@ -115,8 +115,18 @@ sd() {
   point_path="$sdd/$requested_point"
 
   if [[ ! -L "$point_path" ]]; then
-    echo "Can't shift to point '$requested_point' because it doesn't exist."
-    return 1
+    if [ -z "$SD_USE_FZF" ]; then
+        echo "Can't shift to point '$requested_point' because it doesn't exist."
+        return 1
+    else
+        type fzf >/dev/null 2>&1 || {
+        echo  "Can't shift to point '$requested_point' because it doesn't exist."
+        echo  "Also fzf should be used instead, but fzf can't be found."
+        return 1
+        }
+        point_path="$sdd/$(find "$sdd" -maxdepth 1 -type l -printf "%f\n"|fzf -q "$*")"
+    fi
+
   fi
 
   local requested_destination="$(readlink $point_path)/$subpath"
